package com.example.mobile.TagListActivity;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.widget.ListView;
import android.widget.Toast;

import com.example.mobile.EditSummary.EditSummaryActivity;
import com.example.mobile.R;
import com.example.shared.MOMNoteModel;
import com.example.shared.SharedPrefUtils;

import java.util.ArrayList;
import java.util.List;

public class TagNotesListActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_mom_list);

        ListView momListView = findViewById(R.id.mom_list_view);
        Intent intent = getIntent();
        String tag = intent.getStringExtra("tag");
        if (tag == null) {
            Toast.makeText(this, "No tag selected", Toast.LENGTH_SHORT).show();
            finish();
            return;
        }
        setTitle(tag + " Notes");
        List<MOMNoteModel> allNotes = SharedPrefUtils.getAllNotes(this);
        List<MOMNoteModel> filteredNotes = new ArrayList<>();
        for (MOMNoteModel note : allNotes) {
            if (note.getTags() != null && note.getTags().contains(tag)) {
                filteredNotes.add(note);
            }
        }
        TagNotesListAdapter adapter = new TagNotesListAdapter(this, filteredNotes);
        momListView.setAdapter(adapter);
        momListView.setOnItemClickListener((parent, view, position, id) -> {
            MOMNoteModel note = filteredNotes.get(position);

            Intent editIntent = new Intent(TagNotesListActivity.this, EditSummaryActivity.class);
            editIntent.putExtra("note_id", note.getAutogeneratedId()); // Pass original ID
            editIntent.putExtra("title", note.getTitle());
            editIntent.putExtra("minutes", note.getMomdetails());
            editIntent.putExtra("tag", note.getTags() != null && !note.getTags().isEmpty() ? note.getTags().get(0) : "");
            startActivity(editIntent);
        });
    }
}
