package com.example.mobile.TagListActivity;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.widget.Toast;

import com.example.mobile.EditSummary.EditSummaryActivity;
import com.example.mobile.databinding.ActivityMomListBinding;
import com.example.shared.MOMNoteModel;
import com.example.shared.SharedPrefUtils;

import java.util.ArrayList;
import java.util.List;

public class TagNotesListActivity extends Activity {

    // Use View Binding instead of findViewById
    private ActivityMomListBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Initialize view binding
        binding = ActivityMomListBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // Get the selected tag from Intent extras
        Intent intent = getIntent();
        String tag = intent.getStringExtra("tag");

        if (tag == null) {
            // If no tag is provided, show a message and close activity
            Toast.makeText(this, "No tag selected", Toast.LENGTH_SHORT).show();
            finish();
            return;
        }

        // Set the activity title based on the tag
        setTitle(tag + " Notes");

        // Get all notes from SharedPreferences
        List<MOMNoteModel> allNotes = SharedPrefUtils.getAllNotes(this);

        // Filter notes by the selected tag
        List<MOMNoteModel> filteredNotes = new ArrayList<>();
        for (MOMNoteModel note : allNotes) {
            if (note.getTags() != null && note.getTags().contains(tag)) {
                filteredNotes.add(note);
            }
        }

        // Initialize the adapter with the filtered notes
        TagNotesListAdapter adapter = new TagNotesListAdapter(this, filteredNotes);

        // Set the adapter to the ListView using view binding
        binding.momListView.setAdapter(adapter);

        // Handle item clicks
        binding.momListView.setOnItemClickListener((parent, view, position, id) -> {
            MOMNoteModel note = filteredNotes.get(position);

            // Open EditSummaryActivity with the selected note's details
            Intent editIntent = new Intent(TagNotesListActivity.this, EditSummaryActivity.class);
            editIntent.putExtra("note_id", note.getAutogeneratedId()); // Pass original note ID
            editIntent.putExtra("title", note.getTitle());
            editIntent.putExtra("minutes", note.getMomdetails());
            editIntent.putExtra("tag", note.getTags() != null && !note.getTags().isEmpty() ? note.getTags().get(0) : "");
            startActivity(editIntent);
        });

        // Set up back button functionality for Toolbar
        if (binding.topBar != null) {
            binding.topBar.setNavigationOnClickListener(v -> {
                // If using fragments, pop the back stack
                if (getFragmentManager().getBackStackEntryCount() > 0) {
                    getFragmentManager().popBackStack();
                } else {
                    // Otherwise, finish the activity
                    finish();
                }
            });
        }
    }
}
