package com.example.shared;

import java.util.List;

public class MOMNoteModel {
    private String autogeneratedId;
    private String title;
    private String momdetails;
    private List<String> tags;
    private long time;

    public MOMNoteModel(String autogeneratedId, String title, String momdetails, List<String> tags, long time) {
        this.autogeneratedId = autogeneratedId;
        this.title = title;
        this.momdetails = momdetails;
        this.tags = tags;
        this.time = time;
    }

    public String getAutogeneratedId() {
        return autogeneratedId;
    }

    public String getTitle() {
        return title;
    }

    public String getMomdetails() {
        return momdetails;
    }

    public List<String> getTags() {
        return tags;
    }

    public long getTime() {
        return time;
    }

    // You can add setters if needed
}

