package com.example.shared;

import java.util.List;

/**
 * Model class representing a stored MOM (Minutes of Meeting) note.
 * This version is typically used for SharedPreferences or persistent storage.
 */
public class MOMNoteModel {

    // Unique autogenerated ID for each note (used as a key for storage or identification)
    private String autogeneratedId;

    // Title of the note
    private String title;

    // Raw text details of the MOM note
    private String momdetails;

    // List of tags associated with the note (optional)
    private List<String> tags;

    // Timestamp representing when the note was created or stored (milliseconds since epoch)
    private long time;

    /**
     * Constructor to create a new MOMNoteModel.
     *
     * @param autogeneratedId Unique ID for the note
     * @param title           Title of the note
     * @param momdetails      Raw details or text of the meeting
     * @param tags            List of tags/categories associated with the note
     * @param time            Timestamp of the note creation (ms since epoch)
     */
    public MOMNoteModel(String autogeneratedId, String title, String momdetails, List<String> tags, long time) {
        this.autogeneratedId = autogeneratedId;
        this.title = title;
        this.momdetails = momdetails;
        this.tags = tags;
        this.time = time;
    }

    /** @return the autogenerated unique ID of the note */
    public String getAutogeneratedId() {
        return autogeneratedId;
    }

    /** @return the title of the note */
    public String getTitle() {
        return title;
    }

    /** @return the raw MOM text/details of the note */
    public String getMomdetails() {
        return momdetails;
    }

    /** @return list of tags associated with the note */
    public List<String> getTags() {
        return tags;
    }

    /** @return timestamp (milliseconds since epoch) of when the note was created */
    public long getTime() {
        return time;
    }

}
